#!/bin/sh
# Move the mouse automatically to prevent inactivity

# Warn the user that they can interrupt this script
# by closing the terminal window
echo "To stop this script that moves the mouse, please either press 'CTRL+C', 'ALT+F4' or your terminal-specific keybinding."

# Print when this script was started
echo "Started at $(date '+%A, %B %d %Y at %T')"


# While loop that runs the script
while true; do
	# Move the mouse to the top-left corner of the screen
	# and wait 50 seconds
	xdotool mousemove 0 0; sleep 50
	# Move the mouse to x=500 y=500
	# and wait 50 seconds
	xdotool mousemove 500 500; sleep 50
done
