#!/bin/bash
# script launcher, containing all scripts
# list of scripts
scripts=$(cd $HOME/.config/scripts && find . -maxdepth 1 -perm -111 -type f | tr -d "./" | sort)
# ask user which script to run
scriptrun=$(echo "$scripts" | dmenu -i -p "Select which script to run:")
[[ $scriptrun = "" ]] && notify-send -u critical "Launcher" "Please select a script" && exit 1
notify-send "Launcher" "Launching script: $scriptrun" && st $HOME/.config/scripts/$scriptrun
