#!/bin/sh
# This script will reduce brightness to 1,
# will disable the touchpad,
# will disable networking,
# will turn off audio
# will disable microphone
# and will lock the screen.

# Check if doas is installed
# If it is, use it instead of sudo
[ $(which doas) ] && root="doas" || root="sudo"

# Disable the touchpad
xinput --disable 12

# Get a list of network cards
netcards=$(ifconfig | grep -Eo "^(e|v|w)[a-z0-9]+")

# Disable Networking
for card in $netcards
do
	doas ifconfig $card down
done

# Turn off audio and disable microphone
amixer -qD pulse sset Master mute; kill -44 $(pidof dwmblocks)
amixer -qD pulse sset Capture nocap; kill -44 $(pidof dwmblocks)

# Reduce brightness to 1
xbacklight -set 1

# Lock the screen
slock-red -m "WARNING! THIS LAPTOP HAS BEEN INFECTED WITH VIRUS '8r0D0u3v3Nl1fT' PLEASE SEEK IMMEDIATE HELP! "
