#!/bin/bash
# record the screen with ffmpeg
# the script automatically selects the screen size
# requires "dmenu"

# get current PID of running script
curpid=$(ps | grep screenrecord | awk '{print $1}' | tr "\n" " " | tr " " "-")

# check if the recording is still active and end it
[[ $(ls "/tmp" | grep screenrecord) ]] &&
	stoprec=$(printf "Yes\nNo" | dmenu -i -p "Recording is still active. Stop?") &&
	[[ "$stoprec" = "Yes" || "$stoprec" = "yes" ]] &&
	pkill ffmpeg &&
	cd "/tmp" && ls -m | grep -o "screenrecord-[0-9]\+-[0-9]\+-" | xargs -d"\n" rm -v

# get screen resolution
scrres=$(xdpyinfo | awk '/dimensions:/ { print $2 }')

[ ! -d "$HOME/Videos" ] && mkdir -p $HOME/Videos

# ask if user wants to record desktop only, or desktop and audio 
choice=$(printf "Desktop Only\nDesktop and Audio" | dmenu -i -p "Select what to record")

# exit if no input
[ -z "$choice" ] && exit 1

# ask user where to save video
outfile=$(echo "" | dmenu -i -p "Select ONLY the name for the video (it will be saved under ~/Videos)")

# exit if no input
[ -z "$outfile" ] && exit 1

# ask user if the output file should be .mkv or .mp4
outformat=$(printf "mp4\nmkv" | dmenu -i -p "Do you want to save the file as .mp4 or as .mkv?")

# exit if no input
[ -z "$outformat" ] && exit 1

# if the user chose mp4, save the video as $HOME/Videos/file.mp4
[ "$outformat" = "mp4" ] && output="$HOME/Videos/$outfile.mp4"
# if the user chose mkv, save the video as $HOME/Videos/file.mkv
[ "$outformat" = "mkv" ] && output="$HOME/Videos/$outfile.mkv"

# record only the desktop
if [ "$choice" = "Desktop Only" ]; then
	printf "$curpid" > "/tmp/screenrecord-$curpid" && [ -f $(which ffmpeg) ] && ffmpeg -f x11grab -framerate 30 -s $scrres -i :0.0 -c:v libx264 -crf 18 -pix_fmt yuv420p $output
fi

# record desktop and audio
if [ "$choice" = "Desktop and Audio" ]; then
	printf "$curpid" > "/tmp/screenrecord-$curpid" && [ -f $(which ffmpeg) ] && ffmpeg -f x11grab -framerate 30 -s $scrres -i :0.0 -f pulse -i 1 -c:v libx264 -crf 18 -pix_fmt yuv420p -ac 2 $output
fi
